### ISSUE TITLE
[FEATURE] 회원 관리 - 세션 관리, 로그아웃

### ISSUE THREAD

**Issue by jiminh00** [RunningDuk/UniRun-BE#10]
## Description
회원 관리 - 세션 관리, 로그아웃
회원 조회
client-secret 암호화
## Todo
- [ ] 세션 관리 - 아이디 세션 저장
- [ ] 로그 아웃 - 세션 삭제 
- [ ] 회원 조회
- [ ] 카카오 로그인에 필요한 client-secret를 jasypt 사용하여 암호화
