### ISSUE TITLE
[BUG] 러닝 완료 알림 기능 버그

### ISSUE THREAD

**Issue by jiminh00** [RunningDuk/UniRun-BE#16]
## Description

러닝 완료 직후 팝업으로 뜨는 러닝 완료 알림 기능에 관한 버그 수정합니다. 

## Todo
- [x] 러닝 타입 조회 API 버그
   - [x] 당일 러닝 스케줄의 러닝 타입만 조회되도록 수정합니다. 
       (기존에는 사용자가 참여한 모든 러닝 스케줄을 참고하여 러닝 타입을 생성함.)
- [x] 러닝 이름 저장 API 버그
   - [x] 서버 에러에 대한 예외 처리를 추가합니다.
