### ISSUE TITLE
[BUG] 회원 관리 버그 수정

### ISSUE THREAD

**Issue by jiminh00** [RunningDuk/UniRun-BE#27]
## Description

회원 관리 기능의 버그 수정합니다. 

## Todo
- [ ] **회원 정보 조회** API 경로 수정 
- [ ] **회원 탈퇴** API 경로 수정
- [ ] **회원 가입** API Request Body에 지갑 주소 추가
