### ISSUE TITLE
[FEATURE] 러닝 기능 구현

### ISSUE THREAD

**Issue by jiminh00** [RunningDuk/UniRun-BE#3]
## Description

러닝 기능 구현

## Todo
- [x] 웹 소켓을 통한 양방향 통신
   - [x] GPS 데이터를 활용한 러닝 거리, 시간, 칼로리 계산
- [x] 러닝 완료 알림 기능 (러닝명 정하기)
   - [x] 러닝 타입 조회 API
   - [x] 러닝 이름 저장 API
