### ISSUE TITLE
[BUG] 엔티티 클래스 수정 

### ISSUE THREAD

**Issue by jiminh00** [RunningDuk/UniRun-BE#36]
## Description
엔티티 클래스 수정합니다. 

## Todo
- [x] User 클래스 블록체인 지갑 컬럼 추가 
- [x] Nft 클래스 추가
- [x] Reward 클래스 추가
- [x] NftPurchases 클래스 추가
- [x] University 클래스 추가
