### ISSUE TITLE
[REFACTOR] 로그인, 회원가입 로직 변경

### ISSUE THREAD

**Issue by jiminh00** [RunningDuk/UniRun-BE#41]
## Description

로그인, 회원가입 로직 변경

## Todo
- [x] 유니런 서비스 회원 유무 컬럼 추가
- [x] 로그인 로직 변경
  - 회원가입이 필요한 경우, DB에 user_id만 저장
- [x] 회원가입 로직 변경
  - 세션에 저장된 userId를 기반으로 데이터 수정
