### ISSUE TITLE
[BUG] 러닝 파트 로직 수정

### ISSUE THREAD

**Issue by jiminh00** [RunningDuk/UniRun-BE#43]
## Description

러닝 파트 로직 수정합니다. 
기존 : 웹 소켓 연결 이전에 세션 데이터를 통해 유저 정보 접근.
새 로직 : 유저 정보를 제외하고 GPS 데이터를 저장한 후에, API를 통해 러닝 종합 데이터(총 러닝 시간, 러닝 날짜 등)를 업데이트 후, 조회.

## Todo
- [x] GPS 테이블 user_id 컬럼 삭제
- [x] 러닝 종합 데이터 조회 API 구현
- [x] HttpSessionHandShakeIntercepter 삭제
    - 웹 소켓 연결 전 세션 데이터에 접근하기 위함이었음
- [x] 러닝 웹 소켓 중 user_id 사용 부분 삭제
